version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: gridbuddy_selenium-hub
    ports:
      - "4444:4444"
  gridbuddy_chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/Downloads:/home/seluser/Downloads
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=gridbuddy_selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080